### ISSUE TITLE
Add ?redirect=0 to the health-check target 

### ISSUE THREAD

**Issue by gozer** [ziegeer/wiki.mozilla.org#19]
Make it /?redirect=0 instead, that way it avoids redirects

**Comment by ziegeer** [comment]
I don't see health-check target defined anywhere and googling reveals nothing relevant looking, how does that get specified?   I assume this would be in one of the terraform configs.

**Comment by ziegeer** [comment]
Discussed elsewhere.  The ?redirect=0 tells mediawiki to not redirect.  Added health_check_target to the load_balancer module definition in my main.tf which overrides the nubis load_balancer's default variable.  Also had to add mirror this terraform change in Puppet for consul health checks: "check_url => '/?redirect=0'," to web.pp in the nubis_apache class.
