### ISSUE TITLE
Fix aliases

### ISSUE THREAD

**Issue by gozer** [ziegeer/wiki.mozilla.org#23]
From ```
    aliases => [
        { alias            => '/images',
            path             => "/data/www/${project_name}/images",
        },
        { alias            => '/assets',
            path             => "/data/www/${project_name}/assets",
        },
        { alias            => '/extensions',
            path             => "/data/www/${project_name}/extensions",
        },
```

First, the docroot is in /var/www, not /data/www

Second, extensions are going to be under /var/www/${project_name}/core/extensions/ since we moved them all there

**Comment by ziegeer** [comment]
Fixed
